# Generated by Django 5.1.7 on 2025-04-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
