# Generated by Django 5.1.7 on 2025-04-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_usersession_last_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("fretboard", "Fretboard Note Finder")], max_length=50
                    ),
                ),
                ("score", models.IntegerField()),
                ("date_achieved", models.DateTimeField(auto_now_add=True)),
                ("fret_length", models.IntegerField(default=12)),
                ("start_string", models.IntegerField(default=6)),
                ("end_string", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-date_achieved"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "game_type",
                            "fret_length",
                            "start_string",
                            "end_string",
                        ),
                        name="unique_game_config",
                    )
                ],
            },
        ),
    ]
